version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: maham_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: maham_dev
    ports:
      - "5444:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: 
